services:
  fastapi_app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      SECRET_KEY : "UfPEGpDrvk3AdtCPmaaorMFFMkHpCnH1Bv-Qa8pXH4k"

  db:
    image: postgres:18-alpine 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: awrdezcqe1324!
      POSTGRES_DB: careview_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
