"""Replace body_fat_percentage with bmi in HealthMetric

Revision ID: 21275aa39dc1
Revises: f236f10afb2d
Create Date: 2025-11-19 15:38:47.738678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21275aa39dc1'
down_revision: Union[str, Sequence[str], None] = 'f236f10afb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('bmi', sa.Float(), nullable=True))
    op.drop_column('health_metrics', 'body_fat_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('body_fat_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('health_metrics', 'bmi')
    # ### end Alembic commands ###
