"""create onboarding_configs table and finalize user schema

Revision ID: 2f820d6dfe3a
Revises: 2d3bd4473448
Create Date: 2025-11-08 21:41:12.469533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f820d6dfe3a'
down_revision: Union[str, Sequence[str], None] = '2d3bd4473448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('weekly_workout_schedule', sa.Text(), nullable=True),
    sa.Column('workouts_per_week', sa.Integer(), nullable=True),
    sa.Column('intensity_level', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=30), nullable=True),
    sa.Column('activity_level', sa.String(length=30), nullable=True),
    sa.Column('breakfast_time', sa.String(length=10), nullable=True),
    sa.Column('lunch_time', sa.String(length=10), nullable=True),
    sa.Column('dinner_time', sa.String(length=10), nullable=True),
    sa.Column('is_onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarding_configs_id'), 'onboarding_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_configs_id'), table_name='onboarding_configs')
    op.drop_table('onboarding_configs')
    # ### end Alembic commands ###
