"""Update OnboardingConfig to use date_of_birth instead of age

Revision ID: 381444c98748
Revises: 2f2c0f4c07f8
Create Date: 2025-11-15 18:09:43.912919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381444c98748'
down_revision: Union[str, Sequence[str], None] = '2f2c0f4c07f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_configs', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.drop_column('onboarding_configs', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_configs', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('onboarding_configs', 'date_of_birth')
    # ### end Alembic commands ###
