"""Add exercise_duration_hours to health_metrics

Revision ID: 59d155d2259d
Revises: 29da17a7f362
Create Date: 2025-11-19 18:53:20.040317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d155d2259d'
down_revision: Union[str, Sequence[str], None] = '29da17a7f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('exercise_duration_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_metrics', 'exercise_duration_hours')
    # ### end Alembic commands ###
