"""Drop unnecessary meal time columns from onboarding_configs

Revision ID: 7b54676bfe56
Revises: 2f820d6dfe3a
Create Date: 2025-11-11 21:35:21.116418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b54676bfe56'
down_revision: Union[str, Sequence[str], None] = '2f820d6dfe3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_configs', 'breakfast_time')
    op.drop_column('onboarding_configs', 'dinner_time')
    op.drop_column('onboarding_configs', 'lunch_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_configs', sa.Column('lunch_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('onboarding_configs', sa.Column('dinner_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('onboarding_configs', sa.Column('breakfast_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
