"""add_ingredient_allergy

Revision ID: a2a2f0e32c81
Revises: 79b3774f453b
Create Date: 2025-12-07 16:56:33.752016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column # 데이터 삽입을 위해 추가

# revision identifiers, used by Alembic.
revision: str = 'a2a2f0e32c81'
down_revision: Union[str, Sequence[str], None] = '79b3774f453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Inserts data into ingredient_allergen, and skips incorrect op.drop_table commands."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 스키마 변경(op.drop_table)은 제거하고 무시합니다. (pass)
    
    # 2. ingredient_allergen 테이블 데이터 삽입 DML
    ingredient_allergen_table = table(
        'ingredient_allergen',
        column('ingredient_id', sa.Integer),
        column('allergy_id', sa.Integer)
    )

    # 삽입할 데이터 리스트 (ingredient_id, allergy_id)
    # 각 알레르기 ID는 INITIAL_ALLERGIES 리스트의 인덱스 + 1 입니다.
    initial_data = [
        # 곡물/밀 (5: 밀, 35: 호밀)
        {'ingredient_id': 1, 'allergy_id': 5},    # 통밀: 밀
        {'ingredient_id': 20, 'allergy_id': 5},   # 베이글: 밀
        {'ingredient_id': 37, 'allergy_id': 5},   # 파스타면: 밀
        {'ingredient_id': 43, 'allergy_id': 5},   # 밀가루: 밀
        {'ingredient_id': 73, 'allergy_id': 5},   # 밀 또띠아: 밀
        {'ingredient_id': 28, 'allergy_id': 35},  # 호밀: 호밀
        
        # 육류 (9: 돼지고기, 14: 닭고기, 15: 쇠고기)
        {'ingredient_id': 29, 'allergy_id': 9},   # 돼지고기: 돼지고기
        {'ingredient_id': 15, 'allergy_id': 14},  # 닭고기: 닭고기
        {'ingredient_id': 74, 'allergy_id': 14},  # 닭봉: 닭고기
        {'ingredient_id': 25, 'allergy_id': 15},  # 소고기: 쇠고기

        # 유제품 (1: 우유)
        {'ingredient_id': 5, 'allergy_id': 1},    # 요거트: 우유
        {'ingredient_id': 19, 'allergy_id': 1},   # 크림치즈: 우유
        {'ingredient_id': 45, 'allergy_id': 1},   # 버터: 우유
        {'ingredient_id': 48, 'allergy_id': 1},   # 우유: 우유
        {'ingredient_id': 78, 'allergy_id': 1},   # 모짜렐라 치즈: 우유

        # 해산물 (6: 생선, 8: 새우, 17: 조개류)
        {'ingredient_id': 18, 'allergy_id': 6},   # 연어: 생선
        {'ingredient_id': 22, 'allergy_id': 6},   # 참치: 생선
        {'ingredient_id': 36, 'allergy_id': 8},   # 새우: 새우
        {'ingredient_id': 35, 'allergy_id': 17},  # 조개: 조개류

        # 콩/견과류 (2: 대두, 4: 땅콩, 21: 아몬드, 37: 렌틸콩, 38: 병아리콩)
        {'ingredient_id': 12, 'allergy_id': 2},   # 두부: 대두
        {'ingredient_id': 42, 'allergy_id': 4},   # 땅콩: 땅콩
        {'ingredient_id': 11, 'allergy_id': 21},  # 아몬드: 아몬드
        {'ingredient_id': 23, 'allergy_id': 37},  # 렌틸콩: 렌틸콩
        {'ingredient_id': 24, 'allergy_id': 38},  # 병아리콩: 병아리콩

        # 기타 (20: 달걀)
        {'ingredient_id': 3, 'allergy_id': 20},   # 계란: 달걀
    ]

    # 3. 데이터 삽입 실행
    op.bulk_insert(ingredient_allergen_table, initial_data)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Deletes inserted data. Creation of tables is removed to prevent DuplicateTable error."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 데이터 삭제 (downgrade 시 삽입된 데이터 제거)
    op.execute(
        'DELETE FROM ingredient_allergen WHERE ingredient_id IN (1, 20, 37, 43, 73, 28, 29, 15, 74, 25, 5, 19, 45, 48, 78, 18, 22, 36, 35, 12, 42, 11, 23, 24, 3)'
    )
    
    # 이전에 오류를 유발했던 op.create_table 코드는 제거되었습니다.
    # ### end Alembic commands ###
