"""cooking_step - Keep cooking_method, only add cooking_steps

Revision ID: e2d6f2d01539
Revises: af11d159a06f
Create Date: 2025-12-03 22:53:05.704112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d6f2d01539'
down_revision: Union[str, Sequence[str], None] = 'af11d159a06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Only add cooking_steps table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 'cooking_steps' 테이블 생성 (MealItem과의 1:N 관계)
    op.create_table(
        'cooking_steps',
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('step_number', sa.Integer(), nullable=False),
        sa.Column('step_description', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['meal_items.item_id'], name='fk_cooking_steps_meal_items'),
        sa.PrimaryKeyConstraint('step_id')
    )
    
    # 2. 기존에 감지된 item_ingredient 외래 키 추가 (이 부분은 유지)
    #op.create_foreign_key('item_ingredient_ingredient_id_fkey', 'item_ingredient', 'ingredients', ['ingredient_id'], ['ingredient_id'])
    
    # cooking_method 컬럼 제거 로직(op.drop_column)은 삭제됨
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Remove cooking_steps table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 기존에 감지된 item_ingredient 외래 키 제거
    op.drop_constraint('item_ingredient_ingredient_id_fkey', 'item_ingredient', type_='foreignkey')
    
    # 2. 'cooking_steps' 테이블 삭제
    op.drop_table('cooking_steps')
    
    # cooking_method 컬럼 추가 로직(op.add_column)은 삭제됨
    
    # ### end Alembic commands ###
