"""Create all core tables

Revision ID: f236f10afb2d
Revises: 381444c98748
Create Date: 2025-11-15 18:29:02.588810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f236f10afb2d'
down_revision: Union[str, Sequence[str], None] = '381444c98748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_id'), 'health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_health_metrics_recorded_at'), 'health_metrics', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_metrics_recorded_at'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
